[
  {
    name: 'Mutton Chaps',
    secondaryLanguageName: 'لحم الضأن',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.7,
    price: 1.7,
  },
  {
    name: 'Mutton Masala',
    secondaryLanguageName: 'لحم الضأن ماسالا',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.7,
    price: 1.7,
  },
  {
    name: 'Mutton Pepper Masala',
    secondaryLanguageName: 'لحم الضأن الفلفل ماسالا',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.8,
    price: 1.8,
  },
  {
    name: 'Mutton Pepper Chilly',
    secondaryLanguageName: 'لحم الضأن الفلفل البارد',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.8,
    price: 1.8,
  },
  {
    name: 'Botti',
    secondaryLanguageName: 'بوتي',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.4,
    price: 1.4,
  },
  {
    name: 'Mutton Kuruma',
    secondaryLanguageName: 'لحم الضأن كوروما',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.7,
    price: 1.7,
  },
  {
    name: 'Mutton Stew',
    secondaryLanguageName: 'حساء لحم الضأن',
    collectionId: 4,
    description: 'Test Description',
    cost: 1.7,
    price: 1.7,
  },
];
